#!/usr/bin/expect

#created on 14th March 2018
#@author: Abhishek Chattopadhyay
#FName: upgradeRMX
#expect script
#usage: ./upgradeRmx <host> <ssh user> <ssh password> <url> <build> <path>

set timeout 60

set prompt "polycom> "
set root "su - root"
set rootPass "T1TLw@yh@lnut0u"
set url [lindex $argv 3]
set path  [lindex $argv 5]
set build [lindex $argv 4]

spawn ssh [lindex $argv 1]@[lindex $argv 0]

expect "yes/no" { 
	send "yes\r"
	expect "*?assword" { send "[lindex $argv 2]\r" }
	} "*?assword" { send "[lindex $argv 2]\r" }

expect $prompt { send  $root\r }
expect "Password: " { send $rootPass\r }
expect $prompt { send "mount -o remount,rw /data\r" }
expect $prompt { send "cd /data\r" }
expect $prompt { send "ln -sf $build current\r" }
expect $prompt { send "wget $url -P /data/; reboot\r" }

interact














#------------------------Not in use------------ will remove in future
#expect "Password: " { send "[lindex $argv 4]\r" }
#expect $prompt { send "su - [lindex $argv 3]\r" }
#expect $prompt { send scp BuildDownloader.py [lindex $argv 1]@[lindex $argv 0]\r}
#expect $prompt { send "touch /tmp/ok\r" }
#expect $prompt { send "mount -o remount,rw /data\r" }
#expect $prompt { send "mv /output/RMX_*.bin /data\r" }
#expect $prompt { send "ln -sf /data/
